export const M6_PERMISSION_CODES = {
  BILLING_QUERY: 'PERM_M6_BILLING_QUERY',
  BILLING_RECEIPT: 'PERM_M6_BILLING_RECEIPT',
  BILLING_RECONCILE: 'PERM_M6_BILLING_RECONCILE',
  BILLING_RETRY: 'PERM_M6_BILLING_RETRY',
  HISTORY_IMPORT: 'PERM_M6_HISTORY_IMPORT',
  HISTORY_QUERY: 'PERM_M6_HISTORY_QUERY',
  INTEGRATION_TASK_QUERY: 'PERM_M6_INTEGRATION_TASK_QUERY',
  STAT_INDICATOR_QUERY: 'PERM_M6_STAT_INDICATOR_QUERY',
  STAT_REPORT_EXPORT: 'PERM_M6_STAT_REPORT_EXPORT',
  STAT_REPORT_QUERY: 'PERM_M6_STAT_REPORT_QUERY',
  STAT_TEMPLATE_QUERY: 'PERM_M6_STAT_TEMPLATE_QUERY',
} as const;

export const M6_INTEGRATION_PAGE_AUTHORITIES = [
  M6_PERMISSION_CODES.INTEGRATION_TASK_QUERY,
] as const;

export const M6_BILLING_PAGE_AUTHORITIES = [
  M6_PERMISSION_CODES.BILLING_QUERY,
  M6_PERMISSION_CODES.BILLING_RECEIPT,
  M6_PERMISSION_CODES.BILLING_RETRY,
  M6_PERMISSION_CODES.BILLING_RECONCILE,
] as const;

export const M6_HISTORY_PAGE_AUTHORITIES = [
  M6_PERMISSION_CODES.HISTORY_IMPORT,
  M6_PERMISSION_CODES.HISTORY_QUERY,
] as const;

export const M6_STATISTICS_PAGE_AUTHORITIES = [
  M6_PERMISSION_CODES.STAT_INDICATOR_QUERY,
  M6_PERMISSION_CODES.STAT_TEMPLATE_QUERY,
  M6_PERMISSION_CODES.STAT_REPORT_QUERY,
  M6_PERMISSION_CODES.STAT_REPORT_EXPORT,
] as const;

export const M6_ROUTE_ITEMS = [
  {
    codes: M6_STATISTICS_PAGE_AUTHORITIES,
    path: '/m6/quality-indicators',
  },
] as const;
