export const M1_PERMISSION_CODES = {
  BODY_PART_CREATE: 'PERM_SYS_BODY_PART_CREATE',
  BODY_PART_QUERY: 'PERM_SYS_BODY_PART_QUERY',
  CONFIG_QUERY: 'PERM_SYS_CONFIG_QUERY',
  CONFIG_UPDATE: 'PERM_SYS_CONFIG_UPDATE',
  GUIDELINE_CREATE: 'PERM_SYS_GUIDELINE_CREATE',
  GUIDELINE_QUERY: 'PERM_SYS_GUIDELINE_QUERY',
  NUMBERING_QUERY: 'PERM_SYS_NUMBERING_QUERY',
  NUMBERING_UPDATE: 'PERM_SYS_NUMBERING_UPDATE',
  ORDER_CHARGE_CREATE: 'PERM_SYS_ORDER_CHARGE_CREATE',
  ORDER_CHARGE_QUERY: 'PERM_SYS_ORDER_CHARGE_QUERY',
  ORDER_DICT_CREATE: 'PERM_SYS_ORDER_DICT_CREATE',
  ORDER_DICT_QUERY: 'PERM_SYS_ORDER_DICT_QUERY',
  PACKAGE_CREATE: 'PERM_SYS_PACKAGE_CREATE',
  PACKAGE_QUERY: 'PERM_SYS_PACKAGE_QUERY',
  SYSTEM_ROLE_ASSIGN: 'PERM_SYS_ROLE_ASSIGN',
  SYSTEM_ROLE_CREATE: 'PERM_SYS_ROLE_CREATE',
  SYSTEM_ROLE_QUERY: 'PERM_SYS_ROLE_QUERY',
  SYSTEM_USER_CREATE: 'PERM_SYS_USER_CREATE',
  SYSTEM_USER_QUERY: 'PERM_SYS_USER_QUERY',
  SYSTEM_USER_UPDATE: 'PERM_SYS_USER_UPDATE',
  TEMPLATE_CREATE: 'PERM_SYS_TEMPLATE_CREATE',
  TEMPLATE_QUERY: 'PERM_SYS_TEMPLATE_QUERY',
} as const;

export const YES_NO_OPTIONS = [
  { label: '启用', value: true },
  { label: '停用', value: false },
];
