export const M6_PERMISSION_CODES = {
  BILLING_QUERY: 'PERM_M6_BILLING_QUERY',
  HISTORY_IMPORT: 'PERM_M6_HISTORY_IMPORT',
  HISTORY_QUERY: 'PERM_M6_HISTORY_QUERY',
  INTEGRATION_TASK_QUERY: 'PERM_M6_INTEGRATION_TASK_QUERY',
  STAT_INDICATOR_QUERY: 'PERM_M6_STAT_INDICATOR_QUERY',
  STAT_REPORT_EXPORT: 'PERM_M6_STAT_REPORT_EXPORT',
  STAT_REPORT_QUERY: 'PERM_M6_STAT_REPORT_QUERY',
  STAT_TEMPLATE_QUERY: 'PERM_M6_STAT_TEMPLATE_QUERY',
} as const;

export const M6_STAT_CATEGORY_TABS = [
  { label: '质控统计', value: 'QUALITY' },
  { label: '运营统计', value: 'OPERATION' },
  { label: '工作量统计', value: 'WORKLOAD' },
] as const;
