export type BackendMenuComponentDefinition = {
  canonicalTitle?: string;
  component: string;
  componentAliases: string[];
  hideInMenu?: boolean;
  menuCodes?: string[];
  path: string;
  pathAliases?: string[];
  routeName: string;
};

export const BACKEND_MENU_COMPONENT_DEFINITIONS: BackendMenuComponentDefinition[] =
  [
    {
      component: 'BasicLayout',
      componentAliases: ['Layout', 'SystemRoot'],
      menuCodes: ['SYSTEM', 'SYS_MANAGEMENT'],
      path: '/system',
      pathAliases: ['/system'],
      routeName: 'SystemRoot',
    },
    {
      component: '/modules/system-management/views/SystemUsersView',
      componentAliases: ['SystemUsers', 'system/user/index'],
      menuCodes: ['SYS_USERS', 'SYS_USER'],
      path: '/system/users',
      pathAliases: ['/system/users', '/api/v1/system-users'],
      routeName: 'SystemUsers',
    },
    {
      component: '/modules/system-management/views/RolesView',
      componentAliases: ['Roles', 'system/role/index'],
      menuCodes: ['SYS_ROLES', 'SYS_ROLE'],
      path: '/system/roles',
      pathAliases: ['/system/roles', '/api/v1/roles'],
      routeName: 'Roles',
    },
    {
      component: '/modules/system-management/views/DepartmentsView',
      componentAliases: ['Departments', 'system/department/index'],
      menuCodes: ['DEPARTMENTS', 'SYS_DEPT'],
      path: '/system/departments',
      pathAliases: ['/system/departments', '/api/v1/departments'],
      routeName: 'Departments',
    },
    {
      component: '/modules/system-management/views/BodyPartsView',
      componentAliases: ['BodyParts', 'system/body-part/index'],
      menuCodes: ['BODY_PARTS', 'SYS_BODY_PART'],
      path: '/system/body-parts',
      pathAliases: ['/system/body-parts', '/api/v1/body-parts'],
      routeName: 'BodyParts',
    },
    {
      component: '/modules/system-management/views/MedicalOrderDictsView',
      componentAliases: [
        'MedicalOrderDicts',
        'system/medical-order-dict/index',
      ],
      menuCodes: ['ORDER_DICTS', 'SYS_MEDICAL_ORDER_DICT'],
      path: '/system/medical-order-dicts',
      pathAliases: [
        '/system/medical-order-dict',
        '/system/medical-order-dicts',
        '/api/v1/medical-order-dicts',
      ],
      routeName: 'MedicalOrderDicts',
    },
    {
      component: '/modules/system-management/views/MedicalOrderChargesView',
      componentAliases: [
        'MedicalOrderCharges',
        'system/medical-order-charge/index',
      ],
      menuCodes: ['ORDER_CHARGES', 'SYS_MEDICAL_ORDER_CHARGE'],
      path: '/system/medical-order-charges',
      pathAliases: [
        '/system/medical-order-charge',
        '/system/medical-order-charges',
        '/api/v1/medical-order-charge-items',
      ],
      routeName: 'MedicalOrderCharges',
    },
    {
      component: '/modules/system-management/views/MedicalOrderPackagesView',
      componentAliases: [
        'MedicalOrderPackages',
        'system/medical-order-package/index',
      ],
      menuCodes: ['ORDER_PACKAGES', 'SYS_MEDICAL_ORDER_PACKAGE'],
      path: '/system/medical-order-packages',
      pathAliases: [
        '/system/medical-order-packages',
        '/api/v1/medical-order-packages',
      ],
      routeName: 'MedicalOrderPackages',
    },
    {
      component: '/modules/system-management/views/SamplingTemplatesView',
      componentAliases: ['SamplingTemplates', 'system/sampling-template/index'],
      menuCodes: ['SAMPLING_TEMPLATES', 'SYS_SAMPLING_TEMPLATE'],
      path: '/system/sampling-templates',
      pathAliases: ['/system/sampling-templates', '/api/v1/sampling-templates'],
      routeName: 'SamplingTemplates',
    },
    {
      component: '/modules/system-management/views/SamplingGuidelinesView',
      componentAliases: [
        'SamplingGuidelines',
        'system/sampling-guideline/index',
      ],
      menuCodes: ['SAMPLING_GUIDELINES', 'SYS_SAMPLING_GUIDELINE'],
      path: '/system/sampling-guidelines',
      pathAliases: [
        '/system/sampling-guidelines',
        '/api/v1/sampling-guidelines',
      ],
      routeName: 'SamplingGuidelines',
    },
    {
      component: '/modules/system-management/views/SystemConfigsView',
      componentAliases: ['SystemConfigs', 'system/config/index'],
      menuCodes: ['SYSTEM_CONFIGS', 'SYS_CONFIG'],
      path: '/system/configs',
      pathAliases: ['/system/configs', '/api/v1/system-configs'],
      routeName: 'SystemConfigs',
    },
    {
      component: '/modules/system-management/views/NumberingRulesView',
      componentAliases: ['NumberingRules', 'system/numbering-rule/index'],
      menuCodes: ['NUMBERING_RULES', 'SYS_NUMBERING_RULE'],
      path: '/system/numbering-rules',
      pathAliases: ['/system/numbering-rules', '/api/v1/numbering-rules'],
      routeName: 'NumberingRules',
    },
    {
      component: 'BasicLayout',
      componentAliases: ['Dashboard'],
      menuCodes: ['DASHBOARD'],
      path: '/dashboard',
      pathAliases: ['/dashboard'],
      routeName: 'Dashboard',
    },
    {
      component: '/views/dashboard/analytics/index',
      componentAliases: ['Analytics'],
      menuCodes: ['ANALYTICS'],
      path: '/analytics',
      pathAliases: ['/analytics'],
      routeName: 'Analytics',
    },
    {
      component: '/views/dashboard/workspace/index',
      componentAliases: ['Workspace'],
      menuCodes: ['WORKSPACE'],
      path: '/workspace',
      pathAliases: ['/workspace'],
      routeName: 'Workspace',
    },
    {
      component: 'BasicLayout',
      componentAliases: ['WorkflowRoot'],
      menuCodes: ['M2_WORKFLOW'],
      path: '/workflow',
      pathAliases: ['/workflow'],
      routeName: 'WorkflowRoot',
    },
    {
      canonicalTitle: '申请与登记',
      component: '/modules/specimen-workflow/views/SubmissionRegistrationView',
      componentAliases: [
        'ApplicationList',
        'ClinicalRegister',
        'SpecimenManagement',
        'SubmissionRegistration',
      ],
      hideInMenu: true,
      menuCodes: ['M2_APPLICATION_LIST', 'M2_CLINICAL'],
      path: '/workflow/submission-registration',
      pathAliases: [
        '/workflow/submission-registration',
        '/workflow/application-list',
        '/workflow/specimen-management',
        '/workflow/clinical-register',
        '/api/v1/applications',
        '/api/v1/specimens/register',
        '/api/v1/specimen-collections',
      ],
      routeName: 'SubmissionRegistration',
    },
    {
      canonicalTitle: '标本采集',
      component:
        '/modules/specimen-workflow/views/ApplicationRegistrationWorkbenchView',
      componentAliases: ['ApplicationRegistrationWorkbench'],
      menuCodes: ['M2_CLINICAL_WORKBENCH'],
      path: '/workflow/application-registration-workbench',
      pathAliases: ['/workflow/application-registration-workbench'],
      routeName: 'ApplicationRegistrationWorkbench',
    },
    {
      canonicalTitle: '固定与转运',
      component: '/modules/specimen-workflow/views/FixationTransportView',
      componentAliases: [
        'FixationTransport',
        'FixationVerify',
        'TransportHandover',
      ],
      menuCodes: ['M2_FIXATION', 'M2_TRANSPORT'],
      path: '/workflow/fixation-transport',
      pathAliases: [
        '/workflow/fixation-transport',
        '/workflow/fixation-verify',
        '/workflow/transport-handover',
        '/api/v1/specimen-fixations',
        '/api/v1/transport-orders',
      ],
      routeName: 'FixationTransport',
    },
    {
      canonicalTitle: '标本接收工作台',
      component: '/modules/specimen-workflow/views/SpecimenReceiptView',
      componentAliases: ['PathologyReceipt', 'SpecimenReceipt'],
      menuCodes: ['M2_RECEIPT'],
      path: '/workflow/pathology-receipt',
      pathAliases: [
        '/workflow/pathology-receipt',
        '/workflow/specimen-receipt',
        '/api/v1/specimen-receipts',
      ],
      routeName: 'PathologyReceipt',
    },
    {
      canonicalTitle: '追踪与异常',
      component: '/modules/specimen-workflow/views/TrackingQueryView',
      componentAliases: ['TrackingException', 'TrackingQuery'],
      menuCodes: ['M2_TRACKING'],
      path: '/workflow/tracking-exception',
      pathAliases: [
        '/workflow/tracking-exception',
        '/workflow/tracking-query',
        '/api/v1/applications/{id}/tracking',
        '/api/v1/specimens/barcodes/{barcode}/tracking',
      ],
      routeName: 'TrackingException',
    },
    {
      component: 'BasicLayout',
      componentAliases: ['TechnicalWorkflowRoot'],
      menuCodes: ['M3_WORKFLOW'],
      path: '/technical-workflow',
      pathAliases: ['/technical-workflow'],
      routeName: 'TechnicalWorkflowRoot',
    },
    {
      canonicalTitle: '检查登记',
      component:
        '/modules/technical-workflow/views/TechnicalSpecimenRegistrationView',
      componentAliases: ['TechnicalSpecimenRegistration'],
      menuCodes: ['M3_SPECIMEN_REGISTRATION'],
      path: '/technical-workflow/specimen-registration',
      pathAliases: [
        '/technical-workflow/specimen-registration',
        '/api/v1/technical-specimen-registrations/pending',
      ],
      routeName: 'TechnicalSpecimenRegistration',
    },
    {
      canonicalTitle: '常规医嘱工作站',
      component:
        '/modules/technical-workflow/views/RoutineOrderWorkstationView',
      componentAliases: ['RoutineOrderWorkstation'],
      menuCodes: ['M3_ROUTINE_ORDER'],
      path: '/technical-workflow/routine-orders',
      pathAliases: ['/technical-workflow/routine-orders'],
      routeName: 'RoutineOrderWorkstation',
    },
    {
      canonicalTitle: '特检医嘱工作站',
      component:
        '/modules/technical-workflow/views/SpecialOrderWorkstationView',
      componentAliases: ['SpecialOrderWorkstation'],
      menuCodes: ['M3_SPECIAL_ORDER'],
      path: '/technical-workflow/special-orders',
      pathAliases: ['/technical-workflow/special-orders'],
      routeName: 'SpecialOrderWorkstation',
    },
    {
      canonicalTitle: '免疫组化工作站',
      component: '/modules/technical-workflow/views/IhcWorkstationView',
      componentAliases: ['IhcWorkstation'],
      menuCodes: ['M3_IHC'],
      path: '/technical-workflow/ihc',
      pathAliases: ['/technical-workflow/ihc'],
      routeName: 'IhcWorkstation',
    },
    {
      canonicalTitle: '细胞学工作站',
      component: '/modules/technical-workflow/views/CytologyWorkstationView',
      componentAliases: ['CytologyWorkstation'],
      menuCodes: ['M3_CYTOLOGY'],
      path: '/technical-workflow/cytology',
      pathAliases: ['/technical-workflow/cytology'],
      routeName: 'CytologyWorkstation',
    },
    {
      canonicalTitle: '液基细胞学工作站',
      component:
        '/modules/technical-workflow/views/LiquidCytologyWorkstationView',
      componentAliases: ['LiquidCytologyWorkstation'],
      menuCodes: ['M3_LIQUID_CYTOLOGY'],
      path: '/technical-workflow/liquid-cytology',
      pathAliases: ['/technical-workflow/liquid-cytology'],
      routeName: 'LiquidCytologyWorkstation',
    },
    {
      component: '/modules/technical-workflow/views/TechnicalTasksView',
      componentAliases: ['TechnicalTasks'],
      hideInMenu: true,
      menuCodes: ['M3_TASKS'],
      path: '/technical-workflow/tasks',
      pathAliases: [
        '/technical-workflow/tasks',
        '/api/v1/technical-tasks/pending',
      ],
      routeName: 'TechnicalTasks',
    },
    {
      component: '/modules/technical-workflow/views/FrozenWorkstationView',
      componentAliases: ['FrozenWorkstation'],
      hideInMenu: true,
      menuCodes: ['M3_FROZEN'],
      path: '/technical-workflow/frozen',
      pathAliases: ['/technical-workflow/frozen'],
      routeName: 'FrozenWorkstation',
    },
    {
      canonicalTitle: '取材描写工作站',
      component: '/modules/technical-workflow/views/GrossingWorkstationView',
      componentAliases: ['Grossing'],
      menuCodes: ['M3_GROSSING'],
      path: '/technical-workflow/grossing',
      pathAliases: ['/technical-workflow/grossing', '/api/v1/grossings'],
      routeName: 'GrossingWorkstation',
    },
    {
      component: '/modules/technical-workflow/views/DehydrationWorkstationView',
      componentAliases: ['Dehydration'],
      menuCodes: ['M3_DEHYDRATION'],
      path: '/technical-workflow/dehydration',
      pathAliases: [
        '/technical-workflow/dehydration',
        '/api/v1/dehydration-batches',
      ],
      routeName: 'DehydrationWorkstation',
    },
    {
      component: '/modules/technical-workflow/views/EmbeddingWorkstationView',
      componentAliases: ['Embedding'],
      menuCodes: ['M3_EMBEDDING'],
      path: '/technical-workflow/embedding',
      pathAliases: ['/technical-workflow/embedding', '/api/v1/embeddings'],
      routeName: 'EmbeddingWorkstation',
    },
    {
      component: '/modules/technical-workflow/views/SlicingWorkstationView',
      componentAliases: ['Slicing'],
      menuCodes: ['M3_SLICING'],
      path: '/technical-workflow/slicing',
      pathAliases: ['/technical-workflow/slicing', '/api/v1/slicings'],
      routeName: 'SlicingWorkstation',
    },
    {
      canonicalTitle: '染色出片工作站',
      component: '/modules/technical-workflow/views/StainingWorkstationView',
      componentAliases: ['Staining'],
      menuCodes: ['M3_STAINING'],
      path: '/technical-workflow/staining',
      pathAliases: ['/technical-workflow/staining', '/api/v1/slide-stainings'],
      routeName: 'StainingWorkstation',
    },
    {
      component: '/modules/technical-workflow/views/ReworkWorkstationView',
      componentAliases: ['Rework'],
      menuCodes: ['M3_REWORK'],
      path: '/technical-workflow/rework',
      pathAliases: ['/technical-workflow/rework', '/api/v1/rework-orders'],
      routeName: 'ReworkWorkstation',
    },
    {
      component: '/modules/technical-workflow/views/TechnicalTrackingView',
      componentAliases: ['TechnicalTracking'],
      menuCodes: ['M3_TRACKING'],
      path: '/technical-workflow/tracking',
      pathAliases: [
        '/technical-workflow/tracking',
        '/api/v1/pathology-cases/{id}/technical-tracking',
      ],
      routeName: 'TechnicalTracking',
    },
    {
      component: 'BasicLayout',
      componentAliases: ['DoctorWorkflowRoot'],
      menuCodes: ['M4_WORKFLOW'],
      path: '/doctor-workflow',
      pathAliases: ['/doctor-workflow'],
      routeName: 'DoctorWorkflowRoot',
    },
    {
      component: '/modules/doctor-workflow/views/DiagnosisAssignmentView',
      componentAliases: ['DiagnosisAssignment'],
      menuCodes: ['M4_ASSIGN'],
      path: '/doctor-workflow/assignment',
      pathAliases: [
        '/doctor-workflow/assignment',
        '/api/v1/diagnostic-tasks/pending',
      ],
      routeName: 'DiagnosisAssignment',
    },
    {
      canonicalTitle: '诊断平台工作站',
      component: '/modules/doctor-workflow/views/DiagnosisWorkbenchView',
      componentAliases: ['DiagnosisWorkbench'],
      menuCodes: ['M4_WORKBENCH'],
      path: '/doctor-workflow/workbench',
      pathAliases: [
        '/doctor-workflow/workbench',
        '/api/v1/pathology-cases/{id}/diagnostic-workbench',
      ],
      routeName: 'DiagnosisWorkbench',
    },
    {
      component: '/modules/doctor-workflow/views/PathologyReportView',
      componentAliases: ['PathologyReport'],
      menuCodes: ['M4_REPORT'],
      path: '/doctor-workflow/report',
      pathAliases: ['/doctor-workflow/report', '/api/v1/pathology-reports'],
      routeName: 'PathologyReport',
    },
    {
      component: '/modules/doctor-workflow/views/FrozenReportView',
      componentAliases: ['FrozenReport'],
      menuCodes: ['M4_FROZEN_REPORT'],
      path: '/doctor-workflow/frozen-report',
      pathAliases: ['/doctor-workflow/frozen-report'],
      routeName: 'FrozenReport',
    },
    {
      component: '/modules/doctor-workflow/views/ReportTrackingView',
      componentAliases: ['ReportTracking'],
      menuCodes: ['M4_TRACKING'],
      path: '/doctor-workflow/tracking',
      pathAliases: [
        '/doctor-workflow/tracking',
        '/api/v1/pathology-cases/{id}/report-tracking',
      ],
      routeName: 'ReportTracking',
    },
    {
      component: '/modules/doctor-workflow/views/MedicalOrderWorkbenchView',
      componentAliases: ['MedicalOrderWorkbench', 'MedicalOrders'],
      menuCodes: ['M4_MEDICAL_ORDER', 'M4_MEDICAL_ORDERS'],
      path: '/doctor-workflow/medical-orders',
      pathAliases: [
        '/doctor-workflow/medical-orders',
        '/api/v1/medical-orders/pending',
        '/api/v1/medical-orders',
      ],
      routeName: 'MedicalOrderWorkbench',
    },
    {
      component: '/modules/doctor-workflow/views/ReportRevisionView',
      componentAliases: ['ReportRevision'],
      menuCodes: ['M4_REVISION'],
      path: '/doctor-workflow/revision',
      pathAliases: [
        '/doctor-workflow/revision',
        '/api/v1/report-revision-requests',
      ],
      routeName: 'ReportRevision',
    },
    {
      component: '/modules/doctor-workflow/views/ConsultationWorkstationView',
      componentAliases: ['Consultation'],
      menuCodes: ['M4_CONSULTATION'],
      path: '/doctor-workflow/consultation',
      pathAliases: ['/doctor-workflow/consultation', '/api/v1/consultations'],
      routeName: 'Consultation',
    },
    {
      component: 'BasicLayout',
      componentAliases: ['OperationSupportRoot'],
      menuCodes: ['M5_SUPPORT'],
      path: '/operation-support',
      pathAliases: ['/operation-support'],
      routeName: 'OperationSupportRoot',
    },
    {
      component: '/modules/operation-support/views/ArchiveManagementView',
      componentAliases: ['ArchiveManagement'],
      menuCodes: ['M5_ARCHIVE'],
      path: '/operation-support/archive',
      pathAliases: [
        '/operation-support/archive',
        '/api/v1/archive-records/search',
      ],
      routeName: 'ArchiveManagement',
    },
    {
      component: '/views/_core/fallback/MenuPlaceholderView',
      componentAliases: ['BorrowManagement'],
      menuCodes: ['M5_BORROW'],
      path: '/operation-support/borrow',
      pathAliases: ['/operation-support/borrow'],
      routeName: 'BorrowManagement',
    },
    {
      component: 'BasicLayout',
      componentAliases: ['OperationResourceRoot'],
      menuCodes: ['M5_RESOURCE'],
      path: '/operation-resources',
      pathAliases: ['/operation-resources'],
      routeName: 'OperationResourceRoot',
    },
    {
      component: '/modules/operation-support/views/ReagentLedgerView',
      componentAliases: ['ReagentConsumableManagement', 'ReagentLedger'],
      menuCodes: ['M5_REAGENT', 'M5_REAGENT_CONSUMABLE'],
      path: '/operation-resources/reagents',
      pathAliases: [
        '/operation-resources/reagents',
        '/operation-support/reagents',
        '/api/v1/reagents',
      ],
      routeName: 'ReagentConsumableManagement',
    },
    {
      component: '/modules/operation-support/views/EquipmentLedgerView',
      componentAliases: ['EquipmentManagement', 'EquipmentLedger'],
      menuCodes: ['M5_EQUIPMENT', 'M5_DEVICE'],
      path: '/operation-resources/equipment',
      pathAliases: [
        '/operation-resources/equipment',
        '/operation-support/equipment',
        '/api/v1/equipment-records',
      ],
      routeName: 'EquipmentManagement',
    },
    {
      component: '/views/_core/fallback/MenuPlaceholderView',
      componentAliases: ['HazardousChemicalsManagement'],
      menuCodes: ['M5_HAZARDOUS_CHEMICALS'],
      path: '/operation-resources/hazardous-chemicals',
      pathAliases: ['/operation-resources/hazardous-chemicals'],
      routeName: 'HazardousChemicalsManagement',
    },
    {
      component: '/views/_core/fallback/MenuPlaceholderView',
      componentAliases: ['MedicalWasteManagement'],
      menuCodes: ['M5_MEDICAL_WASTE'],
      path: '/operation-resources/medical-waste',
      pathAliases: ['/operation-resources/medical-waste'],
      routeName: 'MedicalWasteManagement',
    },
    {
      component: 'BasicLayout',
      componentAliases: ['M6Root'],
      menuCodes: ['M6_STATISTICS'],
      path: '/m6',
      pathAliases: ['/m6'],
      routeName: 'M6Root',
    },
    {
      component: '/views/_core/fallback/MenuPlaceholderView',
      componentAliases: ['QualityIndicatorStatistics'],
      menuCodes: ['M6_QUALITY_INDICATORS'],
      path: '/m6/quality-indicators',
      pathAliases: ['/m6/quality-indicators'],
      routeName: 'QualityIndicatorStatistics',
    },
    {
      component: '/views/_core/fallback/MenuPlaceholderView',
      componentAliases: ['ManagementIndicatorStatistics'],
      menuCodes: ['M6_MANAGEMENT_INDICATORS'],
      path: '/m6/management-indicators',
      pathAliases: ['/m6/management-indicators'],
      routeName: 'ManagementIndicatorStatistics',
    },
    {
      component: '/modules/m6-statistics/views/StatisticsAnalysisView',
      componentAliases: ['CustomStatisticsAnalysis', 'StatisticsAnalysis'],
      menuCodes: ['M6_CUSTOM_ANALYSIS', 'M6_STAT'],
      path: '/m6/custom-analysis',
      pathAliases: [
        '/m6/custom-analysis',
        '/m6/statistics',
        '/api/v1/stat-indicators',
        '/api/v1/stat-report-templates',
        '/api/v1/stat-reports/query',
        '/api/v1/stat-reports/export',
      ],
      routeName: 'CustomStatisticsAnalysis',
    },
  ];
