import {
  bindSpecimenBarcodeMock,
  checkInSpecimenMock,
  completeFixationMock,
  completeSpecimenVerificationMock,
  confirmSpecimenMock,
  confirmSpecimenRemovalByIdentifierMock,
  confirmSpecimenRemovalMock,
  createApplicationMock,
  createTransportOrderMock,
  deleteApplicationMock,
  directReceiveSpecimensMock,
  duplicateCheckApplicationsMock,
  getApplicationDetailMock,
  getApplicationTrackingByApplicationNoMock,
  getApplicationTrackingMock,
  getLatestRegistrationResultMock,
  getSpecimenTrackingByBarcodeMock,
  handoverTransportOrderMock,
  importClinicalApplicationMock,
  listApplicationsMock,
  listPendingFixationsMock,
  listPendingReceiptsMock,
  listPendingSpecimenRemovalsMock,
  listPendingTransportOrdersMock,
  listSpecimenOutboundsMock,
  listSpecimensMock,
  listSpecimenVerificationRecordsMock,
  lookupApplicationPatientByIdentifierMock,
  lookupApplicationForRegistrationMock,
  outboundTransportOrderMock,
  quickOutboundSpecimenMock,
  printTransportOrderMock,
  rebindSpecimenBarcodeMock,
  receiveSpecimensMock,
  registerSpecimensMock,
  reprintApplicationFormMock,
  resetMockState as resetSpecimenWorkflowMockState,
  retryLabelPrintMock,
  startFixationMock,
  startSpecimenVerificationMock,
  unbindSpecimenBarcodeMock,
  updateApplicationMock,
} from '../specimen-workflow-mock';

export const USE_SPECIMEN_WORKFLOW_MOCK =
  import.meta.env.MODE === 'test' ||
  import.meta.env.VITE_SPECIMEN_WORKFLOW_MOCK === 'true';

export {
  bindSpecimenBarcodeMock,
  checkInSpecimenMock,
  completeFixationMock,
  completeSpecimenVerificationMock,
  confirmSpecimenMock,
  confirmSpecimenRemovalByIdentifierMock,
  confirmSpecimenRemovalMock,
  createApplicationMock,
  createTransportOrderMock,
  deleteApplicationMock,
  directReceiveSpecimensMock,
  duplicateCheckApplicationsMock,
  getApplicationDetailMock,
  getApplicationTrackingByApplicationNoMock,
  getApplicationTrackingMock,
  getLatestRegistrationResultMock,
  getSpecimenTrackingByBarcodeMock,
  handoverTransportOrderMock,
  importClinicalApplicationMock,
  listApplicationsMock,
  listPendingFixationsMock,
  listPendingReceiptsMock,
  listPendingSpecimenRemovalsMock,
  listPendingTransportOrdersMock,
  listSpecimenOutboundsMock,
  listSpecimensMock,
  listSpecimenVerificationRecordsMock,
  lookupApplicationPatientByIdentifierMock,
  lookupApplicationForRegistrationMock,
  outboundTransportOrderMock,
  quickOutboundSpecimenMock,
  printTransportOrderMock,
  rebindSpecimenBarcodeMock,
  receiveSpecimensMock,
  registerSpecimensMock,
  reprintApplicationFormMock,
  resetSpecimenWorkflowMockState,
  retryLabelPrintMock,
  startFixationMock,
  startSpecimenVerificationMock,
  unbindSpecimenBarcodeMock,
  updateApplicationMock,
};
