import type {
  TechnicalWorkbenchPageConfig,
  TechnicalWorkbenchRow,
} from '../types/technical-workbench';

function buildSearchableText(row: Record<string, unknown>) {
  return Object.values(row)
    .filter((value) => value !== null && value !== undefined)
    .map(String)
    .join(' ')
    .toLowerCase();
}

function createRow(row: Omit<TechnicalWorkbenchRow, 'searchableText'>) {
  return {
    ...row,
    searchableText: buildSearchableText(row),
  };
}

const ROUTINE_ORDER_ROWS = [
  createRow({
    id: 'routine-1',
    blockNo: 'A01',
    checkItem: '胃镜活检',
    confirmedStatus: '待确认',
    doctorTime: '08:10',
    doctorUser: '张主任',
    note: '普通切片',
    originalPathologyNo: 'WG-20240618',
    outpatientNo: 'MZ000321',
    patientId: 'P000912',
    patientName: '王淑琴',
    pathologyNo: 'B20250602001',
    printStatus: '未打印',
    printTime: '-',
    releaseStatus: '待出片',
    releaseTime: '-',
    remark: '胃窦 2 块',
    sliceMode: 'NORMAL',
    terminationReason: '-',
    wardNo: 'ZY1208',
    workday: 'today',
  }),
  createRow({
    id: 'routine-2',
    blockNo: 'B03',
    checkItem: '甲状腺穿刺',
    confirmedStatus: '已确认',
    doctorTime: '09:25',
    doctorUser: '李医生',
    note: '快速切片',
    originalPathologyNo: 'TS-20240502',
    outpatientNo: 'MZ000778',
    patientId: 'P000955',
    patientName: '李美荣',
    pathologyNo: 'B20250602002',
    printStatus: '已打印',
    printTime: '09:30',
    releaseStatus: '待出片',
    releaseTime: '-',
    remark: '快速会诊',
    sliceMode: 'RAPID',
    terminationReason: '-',
    wardNo: '门诊',
    workday: 'today',
  }),
  createRow({
    id: 'routine-3',
    blockNo: 'C02',
    checkItem: '肠镜活检',
    confirmedStatus: '待确认',
    doctorTime: '10:05',
    doctorUser: '王医生',
    note: '普通切片',
    originalPathologyNo: 'CJ-20240520',
    outpatientNo: 'MZ000801',
    patientId: 'P000998',
    patientName: '陈建军',
    pathologyNo: 'B20250602003',
    printStatus: '未打印',
    printTime: '-',
    releaseStatus: '待出片',
    releaseTime: '-',
    remark: '降结肠 1 块',
    sliceMode: 'NORMAL',
    terminationReason: '-',
    wardNo: 'ZY0912',
    workday: 'today',
  }),
  createRow({
    id: 'routine-4',
    blockNo: 'D08',
    checkItem: '乳腺肿物',
    confirmedStatus: '待确认',
    doctorTime: '15:40',
    doctorUser: '孙医生',
    note: '普通切片',
    originalPathologyNo: 'RX-20240530',
    outpatientNo: 'MZ000815',
    patientId: 'P001021',
    patientName: '周丽',
    pathologyNo: 'B20250601011',
    printStatus: '未打印',
    printTime: '-',
    releaseStatus: '待出片',
    releaseTime: '-',
    remark: '昨日遗留',
    sliceMode: 'NORMAL',
    terminationReason: '-',
    wardNo: 'ZY1216',
    workday: 'previous',
  }),
  createRow({
    id: 'routine-5',
    blockNo: 'E02',
    checkItem: '淋巴结活检',
    confirmedStatus: '待确认',
    doctorTime: '11:20',
    doctorUser: '刘医生',
    note: '普通切片',
    originalPathologyNo: 'LB-20240601',
    outpatientNo: 'MZ000890',
    patientId: 'P001102',
    patientName: '赵楠',
    pathologyNo: 'B20250603005',
    printStatus: '未打印',
    printTime: '-',
    releaseStatus: '待出片',
    releaseTime: '-',
    remark: '明日预约',
    sliceMode: 'NORMAL',
    terminationReason: '-',
    wardNo: 'ZY1305',
    workday: 'next',
  }),
] as TechnicalWorkbenchRow[];

const SPECIAL_ORDER_ROWS = [
  createRow({
    id: 'special-1',
    checkItem: 'PAS 染色',
    confirmAction: '待确认',
    doctorMessage: '考虑肾穿特染',
    doctorUser: '刘主任',
    doctorTime: '08:45',
    orderAction: '待出片',
    orderType: '特殊染色',
    patientId: 'P200321',
    patientName: '周海燕',
    pathologyNo: 'T20250602001',
    printStatus: '已打印',
    remark: '肾穿',
    revokeReminder: '无',
    wardNo: '肾内科 02',
    workday: 'today',
  }),
  createRow({
    id: 'special-2',
    checkItem: '抗酸染色',
    confirmAction: '已确认',
    doctorMessage: '加做分支杆菌',
    doctorUser: '赵医生',
    doctorTime: '09:50',
    orderAction: '待出片',
    orderType: '病原学',
    patientId: 'P200322',
    patientName: '徐丽',
    pathologyNo: 'T20250602002',
    printStatus: '未打印',
    remark: '肺穿刺',
    revokeReminder: '撤销提醒',
    wardNo: '呼吸科 07',
    workday: 'today',
  }),
  createRow({
    id: 'special-3',
    checkItem: 'Masson 染色',
    confirmAction: '待确认',
    doctorMessage: '纤维化评估',
    doctorUser: '陈医生',
    doctorTime: '14:20',
    orderAction: '待出片',
    orderType: '特殊染色',
    patientId: 'P200355',
    patientName: '钱波',
    pathologyNo: 'T20250601012',
    printStatus: '未打印',
    remark: '昨日延续',
    revokeReminder: '无',
    wardNo: '肝病科 03',
    workday: 'previous',
  }),
] as TechnicalWorkbenchRow[];

const IHC_ROWS = [
  createRow({
    confirmAction: '待确认',
    deviceName: 'Roche-01',
    doctorUser: '郑主任',
    id: 'ihc-1',
    instrumentAction: '待上机',
    pathologyNo: 'I20250602001',
    patientId: 'P300112',
    patientName: '蒋莉',
    plateNo: 'S-01',
    printCallbackResult: '未回传',
    slideNo: 'IHC-001',
    stainingAction: '待染色',
    specimenNo: '蜡块 A1',
    workday: 'today',
  }),
  createRow({
    confirmAction: '已确认',
    deviceName: 'Dako-02',
    doctorUser: '郑主任',
    id: 'ihc-2',
    instrumentAction: '已上机',
    pathologyNo: 'I20250602002',
    patientId: 'P300118',
    patientName: '王磊',
    plateNo: 'S-02',
    printCallbackResult: '成功',
    slideNo: 'IHC-002',
    stainingAction: '待出片',
    specimenNo: '蜡块 B2',
    workday: 'today',
  }),
  createRow({
    confirmAction: '待确认',
    deviceName: 'Roche-01',
    doctorUser: '黄医生',
    id: 'ihc-3',
    instrumentAction: '待上机',
    pathologyNo: 'I20250601015',
    patientId: 'P300156',
    patientName: '陈霞',
    plateNo: 'S-03',
    printCallbackResult: '未回传',
    slideNo: 'IHC-003',
    stainingAction: '待染色',
    specimenNo: '蜡块 C3',
    workday: 'previous',
  }),
] as TechnicalWorkbenchRow[];

const CYTOLOGY_ROWS = [
  createRow({
    blockCount: 2,
    flowStatus: '待出片',
    id: 'cytology-1',
    pathologyNo: 'C20250602001',
    patientId: 'P400111',
    patientName: '陆萍',
    printedBlocks: 1,
    printedSlides: 2,
    receiverName: '王技师',
    releaseUser: '李技师',
    sampleType: '细胞学',
    slideCount: 3,
    specimenName: '胸水',
    submitDept: '呼吸内科',
    tagName: '常规',
    workday: 'today',
  }),
  createRow({
    blockCount: 1,
    flowStatus: '已打玻片',
    id: 'cytology-2',
    pathologyNo: 'C20250602002',
    patientId: 'P400118',
    patientName: '高宁',
    printedBlocks: 1,
    printedSlides: 1,
    receiverName: '王技师',
    releaseUser: '张技师',
    sampleType: '细胞学会诊',
    slideCount: 1,
    specimenName: '尿液',
    submitDept: '泌尿外科',
    tagName: '会诊',
    workday: 'today',
  }),
  createRow({
    blockCount: 1,
    flowStatus: '待固定',
    id: 'cytology-3',
    pathologyNo: 'C20250601009',
    patientId: 'P400130',
    patientName: '邓倩',
    printedBlocks: 0,
    printedSlides: 0,
    receiverName: '赵技师',
    releaseUser: '-',
    sampleType: '细胞学',
    slideCount: 0,
    specimenName: '腹水',
    submitDept: '肿瘤内科',
    tagName: '延迟固定',
    workday: 'previous',
  }),
] as TechnicalWorkbenchRow[];

const LIQUID_CYTOLOGY_ROWS = [
  createRow({
    flowStatus: '待出片',
    id: 'liquid-cytology-1',
    pathologyNo: 'L20250602001',
    patientId: 'P500101',
    patientName: '唐静',
    printedSlides: 1,
    receiverName: '王技师',
    releaseUser: '刘技师',
    sampleType: '妇科液基细胞学',
    submitDept: '妇科门诊',
    workday: 'today',
  }),
  createRow({
    flowStatus: '已打印玻片',
    id: 'liquid-cytology-2',
    pathologyNo: 'L20250602002',
    patientId: 'P500108',
    patientName: '罗娟',
    printedSlides: 2,
    receiverName: '王技师',
    releaseUser: '刘技师',
    sampleType: '非妇科液基细胞学',
    submitDept: '体检中心',
    workday: 'today',
  }),
  createRow({
    flowStatus: '待出片',
    id: 'liquid-cytology-3',
    pathologyNo: 'L20250601010',
    patientId: 'P500122',
    patientName: '胡婷',
    printedSlides: 0,
    receiverName: '赵技师',
    releaseUser: '-',
    sampleType: '妇科液基细胞学',
    submitDept: '妇科住院',
    workday: 'previous',
  }),
] as TechnicalWorkbenchRow[];

export const ROUTINE_ORDER_WORKSTATION_CONFIG: TechnicalWorkbenchPageConfig = {
  columns: [
    {
      formatter: (_, rowIndex) => String(rowIndex + 1),
      key: 'rowIndex',
      label: '序',
      width: 56,
    },
    { key: 'pathologyNo', label: '病理号', minWidth: 132 },
    { key: 'originalPathologyNo', label: '原病理号', minWidth: 132 },
    { key: 'wardNo', label: '住院号', minWidth: 96 },
    { key: 'outpatientNo', label: '门诊号', minWidth: 96 },
    { key: 'blockNo', label: '蜡块号', width: 86 },
    { key: 'patientId', label: '病人ID', minWidth: 98 },
    { key: 'patientName', label: '病人姓名', minWidth: 100 },
    { key: 'checkItem', label: '检查项目', minWidth: 130 },
    { key: 'doctorTime', label: '医嘱时间', minWidth: 100 },
    { key: 'doctorUser', label: '医嘱医生', minWidth: 100 },
    { key: 'confirmedStatus', label: '确认状态', minWidth: 90 },
    { key: 'printStatus', label: '打印状态', minWidth: 90 },
    { key: 'printTime', label: '打印时间', minWidth: 100 },
    { key: 'releaseStatus', label: '出片状态', minWidth: 90 },
    { key: 'releaseTime', label: '出片时间', minWidth: 100 },
    { key: 'remark', label: '备注', minWidth: 120 },
    { key: 'terminationReason', label: '终止原因', minWidth: 120 },
  ],
  defaultPageSize: 30,
  defaultWorkday: 'today',
  description:
    '按照旧工作站的操作顺序整理常规医嘱列表，保留高密度工具栏与单表格主视图。',
  dayTabs: [
    { label: '前1天', value: 'previous' },
    { label: '今天', value: 'today' },
    { label: '后1天', value: 'next' },
  ],
  emptyText: '当前日期暂无常规医嘱数据',
  filters: [
    {
      group: 'slice-mode',
      id: 'routine-normal-slice',
      label: '普通切片',
      predicate: (row) => row.sliceMode === 'NORMAL',
    },
    {
      group: 'slice-mode',
      id: 'routine-rapid-slice',
      label: '快速切片',
      predicate: (row) => row.sliceMode === 'RAPID',
    },
  ],
  queryActions: [
    { id: 'routine-more', label: '更多' },
    { id: 'routine-overdue', label: '过期任务' },
  ],
  rows: ROUTINE_ORDER_ROWS,
  searchPlaceholder: '病理号/病人ID/原病理号',
  showPageHeader: false,
  title: '常规医嘱工作站',
  toolbarGroups: [
    [
      {
        hotkey: 'F8',
        id: 'routine-confirm',
        label: '确认',
        requiresSelection: true,
        tone: 'primary',
      },
      { id: 'routine-print-slide', label: '打印玻片', requiresSelection: true },
      {
        hotkey: 'F9',
        id: 'routine-release',
        label: '出片',
        requiresSelection: true,
      },
      {
        id: 'routine-stop',
        label: '终止',
        requiresSelection: true,
        tone: 'danger',
      },
    ],
    [
      {
        id: 'routine-print-label',
        label: '打印申请单标签',
        requiresSelection: true,
      },
      { id: 'routine-merge', label: '相同项目合片' },
      { id: 'routine-unmerge', label: '取消合片' },
      { id: 'routine-export', label: '导出Excel' },
      { id: 'routine-qc', label: '质控评价' },
    ],
  ],
};

export const SPECIAL_ORDER_WORKSTATION_CONFIG: TechnicalWorkbenchPageConfig = {
  columns: [
    {
      formatter: (_, rowIndex) => String(rowIndex + 1),
      key: 'rowIndex',
      label: '序',
      width: 56,
    },
    { key: 'pathologyNo', label: '病理号', minWidth: 132 },
    { key: 'wardNo', label: '住院号', minWidth: 100 },
    { key: 'patientId', label: '病人ID', minWidth: 100 },
    { key: 'patientName', label: '病人姓名', minWidth: 100 },
    { key: 'checkItem', label: '检查项目', minWidth: 120 },
    { key: 'remark', label: '备注', minWidth: 120 },
    { key: 'orderType', label: '项目类型', minWidth: 96 },
    { key: 'confirmAction', label: '确认操作', minWidth: 90 },
    { key: 'orderAction', label: '出片操作', minWidth: 90 },
    { key: 'doctorUser', label: '医嘱医生', minWidth: 100 },
    { key: 'printStatus', label: '打印状态', minWidth: 90 },
    { key: 'doctorMessage', label: '医嘱留言', minWidth: 140 },
    { key: 'revokeReminder', label: '撤销提醒', minWidth: 100 },
  ],
  defaultPageSize: 100,
  defaultWorkday: 'today',
  description:
    '延续常规医嘱页的信息密度，但突出项目类型、确认操作和撤销提醒等特检字段。',
  dayTabs: [
    { label: '前1天', value: 'previous' },
    { label: '今天', value: 'today' },
    { label: '后1天', value: 'next' },
  ],
  emptyText: '当前日期暂无特检医嘱数据',
  queryActions: [
    { id: 'special-more', label: '更多' },
    { id: 'special-overdue', label: '过期任务' },
    { id: 'special-remind', label: '撤销提醒' },
  ],
  rows: SPECIAL_ORDER_ROWS,
  searchPlaceholder: '病理号/病人ID/病人',
  showPageHeader: false,
  title: '特检医嘱工作站',
  toolbarGroups: [
    [
      {
        hotkey: 'F8',
        id: 'special-confirm',
        label: '确认',
        requiresSelection: true,
        tone: 'primary',
      },
      { id: 'special-print-label', label: '打印标签', requiresSelection: true },
      {
        hotkey: 'F9',
        id: 'special-release',
        label: '出片',
        requiresSelection: true,
      },
      {
        id: 'special-stop',
        label: '终止',
        requiresSelection: true,
        tone: 'danger',
      },
    ],
    [
      { id: 'special-export', label: '导出Excel' },
      {
        id: 'special-change-block',
        label: '改蜡块号',
        requiresSelection: true,
      },
      { id: 'special-qc', label: '质控评价' },
    ],
  ],
};

export const IHC_WORKSTATION_CONFIG: TechnicalWorkbenchPageConfig = {
  columns: [
    {
      formatter: (_, rowIndex) => String(rowIndex + 1),
      key: 'rowIndex',
      label: '序',
      width: 56,
    },
    { key: 'patientId', label: '病人ID', minWidth: 100 },
    { key: 'pathologyNo', label: '原病理号', minWidth: 132 },
    { key: 'slideNo', label: '病理号', minWidth: 110 },
    { key: 'patientName', label: '病人', minWidth: 90 },
    { key: 'specimenNo', label: '蜡块号', minWidth: 96 },
    { key: 'plateNo', label: '玻片序号', minWidth: 96 },
    { key: 'confirmAction', label: '确认操作', minWidth: 90 },
    { key: 'instrumentAction', label: '上机操作', minWidth: 90 },
    { key: 'stainingAction', label: '出片操作', minWidth: 90 },
    { key: 'deviceName', label: '分配设备', minWidth: 100 },
    { key: 'doctorUser', label: '医嘱医生', minWidth: 100 },
    { key: 'printCallbackResult', label: '打印指令回传结果', minWidth: 140 },
  ],
  defaultPageSize: 100,
  defaultWorkday: 'today',
  description:
    '保留 Roche / Dako 入口和待确认计数，用统一 Web 骨架承载上机、染色与出片动作。',
  dayTabs: [
    { label: '今天', value: 'today' },
    { label: '前1天', value: 'previous' },
    { label: '后1天', value: 'next' },
  ],
  emptyText: '当前日期暂无免疫组化任务',
  metrics: [
    {
      id: 'ihc-pending-confirm',
      label: '待确认',
      tone: 'danger',
      value: (rows) =>
        rows.filter((row) => row.confirmAction === '待确认').length,
    },
    {
      id: 'ihc-confirmed-today',
      label: '本人今日确认',
      tone: 'success',
      value: (rows) =>
        rows.filter((row) => row.confirmAction === '已确认').length,
    },
  ],
  queryActions: [
    { id: 'ihc-more', label: '更多' },
    { id: 'ihc-overdue', label: '过期任务' },
    { id: 'ihc-change-remind', label: '变更提醒' },
  ],
  rows: IHC_ROWS,
  searchPlaceholder: '病理号/检查项/病人',
  showPageHeader: false,
  title: '免疫组化工作站',
  toolbarGroups: [
    [
      { id: 'ihc-roche', label: 'Roche标签' },
      { id: 'ihc-dako', label: 'Dako标签' },
      {
        id: 'ihc-confirm',
        label: '确认',
        requiresSelection: true,
        tone: 'primary',
      },
      { id: 'ihc-stain', label: '染色', requiresSelection: true },
      { id: 'ihc-release', label: '出片', requiresSelection: true },
    ],
  ],
};

export const CYTOLOGY_WORKSTATION_CONFIG: TechnicalWorkbenchPageConfig = {
  columns: [
    {
      formatter: (_, rowIndex) => String(rowIndex + 1),
      key: 'rowIndex',
      label: '序',
      width: 56,
    },
    { key: 'sampleType', label: '送检类型', minWidth: 120 },
    { key: 'pathologyNo', label: '病理号', minWidth: 132 },
    { key: 'patientName', label: '病人', minWidth: 90 },
    { key: 'patientId', label: '病人ID', minWidth: 100 },
    { key: 'flowStatus', label: '流程状态', minWidth: 100 },
    { key: 'printedBlocks', label: '已打蜡块', minWidth: 96, align: 'center' },
    { key: 'printedSlides', label: '已打玻片', minWidth: 96, align: 'center' },
    { key: 'blockCount', label: '蜡块数', minWidth: 80, align: 'center' },
    { key: 'slideCount', label: '玻片数', minWidth: 80, align: 'center' },
    { key: 'tagName', label: '标本', minWidth: 90 },
    { key: 'submitDept', label: '送检科室', minWidth: 120 },
    { key: 'receiverName', label: '接收人', minWidth: 90 },
    { key: 'releaseUser', label: '出片人', minWidth: 90 },
  ],
  defaultPageSize: 100,
  defaultWorkday: 'today',
  description:
    '围绕细胞学送检流转组织页面，保留生成蜡块、打印蜡块和延迟固定等传统入口。',
  dayTabs: [
    { label: '前1天', value: 'previous' },
    { label: '今天', value: 'today' },
    { label: '后1天', value: 'next' },
  ],
  emptyText: '当前日期暂无细胞学任务',
  queryActions: [
    {
      id: 'cytology-generate-block',
      label: '生成蜡块',
      requiresSelection: true,
    },
    { id: 'cytology-print-block', label: '打印蜡块', requiresSelection: true },
    { id: 'cytology-pending-slide', label: '待打印玻片列表(0)' },
    { id: 'cytology-delay-fixation', label: '延迟固定' },
    { id: 'cytology-overdue', label: '过期任务' },
  ],
  rows: CYTOLOGY_ROWS,
  searchPlaceholder: '病人ID/病理号',
  showPageHeader: false,
  title: '细胞学工作站',
  toolbarGroups: [
    [
      { id: 'cytology-qc', label: '质控评价' },
      { id: 'cytology-green-doctor', label: '特检医嘱' },
      {
        id: 'cytology-release',
        label: '出片',
        requiresSelection: true,
        tone: 'primary',
      },
    ],
  ],
};

export const LIQUID_CYTOLOGY_WORKSTATION_CONFIG: TechnicalWorkbenchPageConfig =
  {
    columns: [
      {
        formatter: (_, rowIndex) => String(rowIndex + 1),
        key: 'rowIndex',
        label: '序',
        width: 56,
      },
      { key: 'pathologyNo', label: '病理号', minWidth: 132 },
      { key: 'patientName', label: '病人', minWidth: 90 },
      {
        key: 'printedSlides',
        label: '已打玻片',
        minWidth: 96,
        align: 'center',
      },
      { key: 'flowStatus', label: '流程状态', minWidth: 100 },
      { key: 'patientId', label: '病人ID', minWidth: 100 },
      { key: 'submitDept', label: '送检科室', minWidth: 120 },
      { key: 'receiverName', label: '接收人', minWidth: 90 },
      { key: 'releaseUser', label: '出片人', minWidth: 90 },
    ],
    defaultPageSize: 100,
    defaultWorkday: 'today',
    description:
      '保持液基细胞学页面的极简工具栏，只突出出片、打印玻片和过期任务入口。',
    dayTabs: [
      { label: '前1天', value: 'previous' },
      { label: '今天', value: 'today' },
      { label: '后1天', value: 'next' },
    ],
    emptyText: '当前日期暂无液基细胞学任务',
    queryActions: [{ id: 'liquid-cytology-overdue', label: '过期任务' }],
    rows: LIQUID_CYTOLOGY_ROWS,
    searchPlaceholder: '病人ID/病理号',
    showPageHeader: false,
    title: '液基细胞学工作站',
    toolbarGroups: [
      [
        {
          id: 'liquid-cytology-release',
          label: '出片',
          requiresSelection: true,
          tone: 'primary',
        },
        {
          hotkey: 'F8',
          id: 'liquid-cytology-print-slide',
          label: '打印玻片',
          requiresSelection: true,
        },
        { id: 'liquid-cytology-qc', label: '质控评价' },
      ],
    ],
  };
