import { describe, expect, it } from 'vitest';

import {
  buildAutoCreatedApplicationPayload,
  buildAutoGeneratedWorkbenchPatientInfo,
  isApplicationNoTooLong,
} from './application-registration-auto-create';
import { normalizeLegacyGeneratedPatientIdNo } from './patient-id-normalization';

describe('application registration auto create helpers', () => {
  it('builds stable simulated application and workbench payloads', () => {
    const firstApplication = buildAutoCreatedApplicationPayload(' AUTO-1188 ');
    const secondApplication = buildAutoCreatedApplicationPayload('AUTO-1188');
    const workbenchPayload = buildAutoGeneratedWorkbenchPatientInfo(
      null,
      { id: 'app-auto-1188' },
      'AUTO-1188',
    );

    expect(secondApplication).toEqual(firstApplication);
    expect(firstApplication).toMatchObject({
      applicationFormStatus: 'PENDING',
      applicationNo: 'AUTO-1188',
      applicationType: 'ROUTINE',
    });
    expect(firstApplication.clinicalDiagnosis).not.toContain('待补充');
    expect(firstApplication.patientName).not.toContain('待补充');
    expect(firstApplication.patientAge).toMatch(/^\d+$/);
    expect(firstApplication.patientId).toMatch(/^\d{5}$/);
    expect(firstApplication.specimenRemovalTime).toMatch(
      /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}$/,
    );
    expect(workbenchPayload.patientInfo).toMatchObject({
      age: expect.stringMatching(/^\d+岁$/),
      applicationNo: 'AUTO-1188',
      idNo: expect.stringMatching(/^\d{5}$/),
      patientName: firstApplication.patientName,
      patientVerified: true,
    });
    expect(workbenchPayload.patientInfo.clinicalHistory).not.toContain(
      '待补充',
    );
    expect(workbenchPayload.patientInfo.remark).not.toContain('记录ID');
    expect(workbenchPayload.contagiousSpecimen).toEqual(
      expect.objectContaining({
        hepatitis: expect.any(Boolean),
        hiv: expect.any(Boolean),
        isolation: expect.any(Boolean),
        syphilis: expect.any(Boolean),
        tuberculosis: expect.any(Boolean),
      }),
    );
    expect(workbenchPayload.surgeryInfo).toEqual(
      expect.objectContaining({
        buildingId: expect.stringMatching(/^B\d{3}$/),
        clinicalFindings: expect.any(String),
        fixationPerson: expect.any(String),
        fixationTime: expect.stringMatching(
          /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/,
        ),
        roomId: expect.stringMatching(/^OR-\d{3}$/),
        specimenRemovalTime: expect.stringMatching(
          /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/,
        ),
        surgeryName: expect.any(String),
      }),
    );
    expect(workbenchPayload.gynecologyInfo.specialConditions).toEqual(
      expect.objectContaining({
        abnormalBleeding: expect.any(Boolean),
        birthControl: expect.any(Boolean),
        hormoneReplacement: expect.any(Boolean),
        hysterectomy: expect.any(Boolean),
        iud: expect.any(Boolean),
        lactation: expect.any(Boolean),
        menopause: expect.any(Boolean),
        pregnancy: expect.any(Boolean),
        radiotherapy: expect.any(Boolean),
      }),
    );
  });

  it('keeps generated fields inside backend dto length limits', () => {
    const application = buildAutoCreatedApplicationPayload('AUTO-LENGTH-001');
    const workbenchPayload = buildAutoGeneratedWorkbenchPatientInfo(
      null,
      { id: 'app-auto-length' },
      'AUTO-LENGTH-001',
    );

    expect(application.applicationNo?.length).toBeLessThanOrEqual(64);
    expect(workbenchPayload.patientInfo.age?.length).toBeLessThanOrEqual(32);
    expect(
      workbenchPayload.patientInfo.applicationDate?.length,
    ).toBeLessThanOrEqual(32);
    expect(workbenchPayload.patientInfo.applyDept.length).toBeLessThanOrEqual(
      100,
    );
    expect(workbenchPayload.patientInfo.applyDoctor.length).toBeLessThanOrEqual(
      100,
    );
    expect(workbenchPayload.patientInfo.checkItem?.length).toBeLessThanOrEqual(
      200,
    );
    expect(
      workbenchPayload.patientInfo.clinicalDiagnosis?.length,
    ).toBeLessThanOrEqual(500);
    expect(
      workbenchPayload.patientInfo.clinicalHistory?.length,
    ).toBeLessThanOrEqual(1000);
    expect(workbenchPayload.patientInfo.phone?.length).toBeLessThanOrEqual(32);
    expect(workbenchPayload.patientInfo.remark?.length).toBeLessThanOrEqual(
      500,
    );
    expect(
      workbenchPayload.surgeryInfo.surgeryName?.length,
    ).toBeLessThanOrEqual(200);
    expect(
      workbenchPayload.gynecologyInfo.specialConditions.other.length,
    ).toBeLessThanOrEqual(500);
  });

  it('detects overlong application numbers after trimming', () => {
    expect(isApplicationNoTooLong(` ${'A'.repeat(64)} `)).toBe(false);
    expect(isApplicationNoTooLong('A'.repeat(65))).toBe(true);
  });

  it('normalizes only legacy generated ID-prefix values', () => {
    expect(normalizeLegacyGeneratedPatientIdNo('ID08305')).toBe('08305');
    expect(normalizeLegacyGeneratedPatientIdNo('320101199001011234')).toBe(
      '320101199001011234',
    );
    expect(normalizeLegacyGeneratedPatientIdNo('ABC123')).toBe('ABC123');
    expect(normalizeLegacyGeneratedPatientIdNo('')).toBe('');
    expect(normalizeLegacyGeneratedPatientIdNo(null)).toBeNull();
  });
});
