import type {
  ApplicationRegistrationWorkbenchRecord,
  SaveApplicationRegistrationPatientInfoRequest,
} from '../types/application-registration-workbench';
import type {
  ApplicationCreateRequest,
  ApplicationCreateResult,
} from '../types/specimen-workflow';

type AutoGeneratedApplicationContext = {
  age: string;
  applicationDate: string;
  applicationNo: string;
  applyDept: string;
  applyDoctor: string;
  backendAge: string;
  bedNo: string;
  checkItem: string;
  clinicalDiagnosis: string;
  clinicalFindings: string;
  clinicalHistory: string;
  contagiousSpecimen: SaveApplicationRegistrationPatientInfoRequest['contagiousSpecimen'];
  deliveryRequirement: string;
  endoscopyDiagnosis: string;
  fixationPerson: string;
  fixationTime: string;
  fixativeType: string;
  frozenReminder: boolean;
  gender: string;
  gynecologyInfo: SaveApplicationRegistrationPatientInfoRequest['gynecologyInfo'];
  idNo: string;
  imagingResult: string;
  inpatientNo: string;
  patientName: string;
  patientVerified: boolean;
  phone: string;
  remark: string;
  roomId: string;
  sourceHospitalName: string;
  specimenRemovalTime: string;
  specimenSite: string;
  specimenType: string;
  submittingDepartmentId: string;
  submittingDoctorUserId: string;
  surgeryBuildingId: string;
  surgeryName: string;
  wardName: string;
};

const sampleProfiles = [
  {
    applyDept: '普外科',
    applyDoctor: '刘强',
    checkItem: '乳腺肿物活检',
    clinicalDiagnosis: '乳腺增生伴结节',
    clinicalFindings: '右乳外上象限可触及约1.5cm结节，边界尚清。',
    clinicalHistory: '发现乳腺结节2周，拟行切除后病理明确性质。',
    deliveryRequirement: '双人核对后送检',
    endoscopyDiagnosis: '无',
    gender: '女',
    imagingResult: '超声示右乳外上象限低回声结节，BI-RADS 4A。',
    specimenSite: '乳腺',
    surgeryName: '乳腺肿物切除术',
    wardName: '普外科病区 8B',
  },
  {
    applyDept: '妇科',
    applyDoctor: '王丽',
    checkItem: '妇科病理检查',
    clinicalDiagnosis: '宫颈上皮内病变待排',
    clinicalFindings: '宫颈局部醋酸白上皮，接触性出血少量。',
    clinicalHistory: '阴道不规则流血1月，门诊筛查提示宫颈异常。',
    deliveryRequirement: '标本离体后立即送检',
    endoscopyDiagnosis: '阴道镜提示宫颈3点位异常区',
    gender: '女',
    imagingResult: '阴道镜示宫颈转化区局灶异常。',
    specimenSite: '宫颈',
    surgeryName: '宫颈活检术',
    wardName: '妇科病区 3A',
  },
  {
    applyDept: '骨科',
    applyDoctor: '张宏',
    checkItem: '手术标本检查与诊断',
    clinicalDiagnosis: '慢性骨髓炎',
    clinicalFindings: '胫骨近端骨质破坏，周围软组织充血水肿。',
    clinicalHistory: '右膝疼痛伴活动受限3月，抗感染治疗后仍反复。',
    deliveryRequirement: '2小时内送达病理科',
    endoscopyDiagnosis: '无',
    gender: '男',
    imagingResult: 'MRI提示右胫骨骨髓水肿并滑膜增厚。',
    specimenSite: '骨组织',
    surgeryName: '右侧胫骨病灶清创术',
    wardName: '骨科病区 5C',
  },
] as const;

const patientNames = [
  '林晓芸',
  '陈宇航',
  '周雨晴',
  '许嘉宁',
  '赵明轩',
] as const;
const operatingRooms = [
  { buildingId: 'B001', roomId: 'OR-101' },
  { buildingId: 'B001', roomId: 'OR-102' },
  { buildingId: 'B002', roomId: 'OR-201' },
] as const;

function normalizeApplicationNo(applicationNo: string) {
  return applicationNo.trim();
}

function hashText(value: string) {
  return [...value].reduce(
    (hash, char) => (hash * 31 + (char.codePointAt(0) ?? 0)) % 100_000,
    17,
  );
}

function pickByHash<T>(items: readonly T[], hash: number) {
  return items[hash % items.length] as T;
}

function padNumber(value: number, length: number) {
  return String(value).padStart(length, '0');
}

function createDateFromHash(hash: number) {
  const day = (hash % 20) + 1;
  return `2026-06-${padNumber(day, 2)}`;
}

function createDateTimeFromHash(hash: number, offsetMinutes = 0) {
  const day = (hash % 20) + 1;
  const hour = 8 + (hash % 8);
  const minute = (hash * 7 + offsetMinutes) % 60;
  const second = (hash * 13 + offsetMinutes) % 60;
  return `2026-06-${padNumber(day, 2)} ${padNumber(hour, 2)}:${padNumber(
    minute,
    2,
  )}:${padNumber(second, 2)}`;
}

function toBackendLocalDateTime(value: string) {
  return value.replace(' ', 'T');
}

function createSpecialConditions(
  hash: number,
  gender: string,
): AutoGeneratedApplicationContext['gynecologyInfo']['specialConditions'] {
  const female = gender === '女';
  const menopause = female && hash % 5 === 0;
  return {
    abnormalBleeding: female && hash % 3 === 0,
    birthControl: female && hash % 4 === 0,
    hormoneReplacement: menopause && hash % 2 === 0,
    hysterectomy: female && hash % 11 === 0,
    iud: female && hash % 7 === 0,
    lactation: female && hash % 13 === 0,
    menopause,
    other: hash % 9 === 0 ? '自动生成：需采集人员复核特殊情况' : '',
    pregnancy: female && !menopause && hash % 10 === 0,
    radiotherapy: hash % 8 === 0,
  };
}

function createAutoGeneratedContext(
  applicationNo: string,
): AutoGeneratedApplicationContext {
  const normalizedApplicationNo = normalizeApplicationNo(applicationNo);
  const hash = hashText(normalizedApplicationNo);
  const profile = pickByHash(sampleProfiles, hash);
  const patientName = pickByHash(patientNames, hash);
  const room = pickByHash(operatingRooms, hash);
  const applicationDate = createDateFromHash(hash);
  const fixationTime = createDateTimeFromHash(hash, 17);
  const specimenRemovalTime = createDateTimeFromHash(hash, 4);
  const numericSuffix = padNumber(hash, 5);
  const ageNumber = 28 + (hash % 41);
  const specialConditions = createSpecialConditions(hash, profile.gender);
  const contagiousSpecimen = {
    hepatitis: hash % 6 === 0,
    hiv: hash % 17 === 0,
    isolation: hash % 5 === 0,
    syphilis: hash % 13 === 0,
    tuberculosis: hash % 11 === 0,
  };

  return {
    age: `${ageNumber}岁`,
    backendAge: String(ageNumber),
    applicationDate,
    applicationNo: normalizedApplicationNo,
    applyDept: profile.applyDept,
    applyDoctor: profile.applyDoctor,
    bedNo: `${(hash % 40) + 1}床`,
    checkItem: profile.checkItem,
    clinicalDiagnosis: profile.clinicalDiagnosis,
    clinicalFindings: profile.clinicalFindings,
    clinicalHistory: profile.clinicalHistory,
    contagiousSpecimen,
    deliveryRequirement: profile.deliveryRequirement,
    endoscopyDiagnosis: profile.endoscopyDiagnosis,
    fixativeType: '10%中性福尔马林',
    fixationPerson: pickByHash(['赵护士', '陈医生', '周永坚'] as const, hash),
    fixationTime,
    frozenReminder: profile.applyDept === '妇科' && hash % 2 === 0,
    gender: profile.gender,
    gynecologyInfo: {
      additionalNotes:
        profile.applyDept === '妇科'
          ? '自动生成妇科专项信息，采集前请复核。'
          : '自动生成申请单，妇科专项信息按常规阴性模板生成。',
      hpvResult:
        profile.applyDept === '妇科' && hash % 2 === 0
          ? '高危型HPV阳性'
          : '阴性',
      lastMenstrualPeriod:
        profile.gender === '女'
          ? `2026-05-${padNumber((hash % 20) + 1, 2)}`
          : '',
      menopause: specialConditions.menopause,
      previousCytology:
        profile.applyDept === '妇科' ? 'ASC-US待复核' : '既往检查未见异常',
      previousTreatment:
        profile.applyDept === '妇科' ? '既往阴道镜检查后随访' : '无',
      specialConditions,
    },
    idNo: `ID${numericSuffix}`,
    imagingResult: profile.imagingResult,
    inpatientNo: `ZY${numericSuffix}`,
    patientName,
    patientVerified: true,
    phone: `138${padNumber(hash, 8)}`,
    remark: `申请单 ${normalizedApplicationNo} 由标本采集查询自动创建，仿真数据待人工复核。`,
    roomId: room.roomId,
    sourceHospitalName: '院内自动创建',
    specimenRemovalTime,
    specimenSite: profile.specimenSite,
    specimenType: '常规',
    submittingDepartmentId: `AUTO-DEPT-${profile.applyDept}`,
    submittingDoctorUserId: `AUTO-DOC-${numericSuffix}`,
    surgeryBuildingId: room.buildingId,
    surgeryName: profile.surgeryName,
    wardName: profile.wardName,
  };
}

function useGeneratedText(
  existingValue: null | string | undefined,
  generated: null | string | undefined,
) {
  return existingValue?.trim() || generated || '';
}

export function buildAutoCreatedApplicationPayload(
  applicationNo: string,
): ApplicationCreateRequest {
  const context = createAutoGeneratedContext(applicationNo);

  return {
    applicationDate: context.applicationDate,
    applicationFormStatus: 'PENDING',
    applicationNo: context.applicationNo,
    applicationType: 'ROUTINE',
    clinicalDiagnosis: context.clinicalDiagnosis,
    patientAge: context.backendAge,
    patientGender: context.gender,
    patientId: context.idNo,
    patientName: context.patientName,
    remarks: context.remark,
    sourceHospitalName: context.sourceHospitalName,
    specimenRemovalTime: toBackendLocalDateTime(context.specimenRemovalTime),
    specimenSite: context.specimenSite,
    submissionDate: context.applicationDate,
    submittingDepartmentId: context.submittingDepartmentId,
    submittingDepartmentName: context.applyDept,
    submittingDoctorName: context.applyDoctor,
    submittingDoctorUserId: context.submittingDoctorUserId,
  };
}

export function buildAutoGeneratedWorkbenchPatientInfo(
  record: ApplicationRegistrationWorkbenchRecord | null,
  created: ApplicationCreateResult,
  applicationNo: string,
): SaveApplicationRegistrationPatientInfoRequest {
  const context = createAutoGeneratedContext(applicationNo);
  const patientInfo = record?.patientInfo;
  const gynecologyInfo = record?.gynecologyInfo;
  const surgeryInfo = record?.surgeryInfo;

  return {
    contagiousSpecimen: {
      ...context.contagiousSpecimen,
      ...record?.contagiousSpecimen,
    },
    gynecologyInfo: {
      ...context.gynecologyInfo,
      ...gynecologyInfo,
      additionalNotes: useGeneratedText(
        gynecologyInfo?.additionalNotes,
        context.gynecologyInfo.additionalNotes,
      ),
      hpvResult: useGeneratedText(
        gynecologyInfo?.hpvResult,
        context.gynecologyInfo.hpvResult,
      ),
      lastMenstrualPeriod: useGeneratedText(
        gynecologyInfo?.lastMenstrualPeriod,
        context.gynecologyInfo.lastMenstrualPeriod,
      ),
      previousCytology: useGeneratedText(
        gynecologyInfo?.previousCytology,
        context.gynecologyInfo.previousCytology,
      ),
      previousTreatment: useGeneratedText(
        gynecologyInfo?.previousTreatment,
        context.gynecologyInfo.previousTreatment,
      ),
      specialConditions: {
        ...context.gynecologyInfo.specialConditions,
        ...gynecologyInfo?.specialConditions,
        other: useGeneratedText(
          gynecologyInfo?.specialConditions?.other,
          context.gynecologyInfo.specialConditions.other,
        ),
      },
    },
    patientInfo: {
      age: useGeneratedText(patientInfo?.age, context.age),
      applicationDate: useGeneratedText(
        patientInfo?.applicationDate,
        context.applicationDate,
      ),
      applicationNo: useGeneratedText(
        patientInfo?.applicationNo,
        context.applicationNo,
      ),
      applyDept: useGeneratedText(patientInfo?.applyDept, context.applyDept),
      applyDoctor: useGeneratedText(
        patientInfo?.applyDoctor,
        context.applyDoctor,
      ),
      bedNo: useGeneratedText(patientInfo?.bedNo, context.bedNo),
      checkItem: useGeneratedText(patientInfo?.checkItem, context.checkItem),
      clinicalDiagnosis: useGeneratedText(
        patientInfo?.clinicalDiagnosis,
        context.clinicalDiagnosis,
      ),
      clinicalHistory: useGeneratedText(
        patientInfo?.clinicalHistory,
        context.clinicalHistory,
      ),
      deliveryRequirement: useGeneratedText(
        patientInfo?.deliveryRequirement,
        context.deliveryRequirement,
      ),
      endoscopyDiagnosis: useGeneratedText(
        patientInfo?.endoscopyDiagnosis,
        context.endoscopyDiagnosis,
      ),
      frozenReminder: patientInfo?.frozenReminder ?? context.frozenReminder,
      gender: useGeneratedText(patientInfo?.gender, context.gender),
      idNo: useGeneratedText(patientInfo?.idNo, context.idNo),
      imagingResult: useGeneratedText(
        patientInfo?.imagingResult,
        context.imagingResult,
      ),
      inpatientNo: useGeneratedText(
        patientInfo?.inpatientNo,
        context.inpatientNo,
      ),
      patientName: useGeneratedText(
        patientInfo?.patientName,
        context.patientName,
      ),
      patientVerified: patientInfo?.patientVerified ?? context.patientVerified,
      phone: useGeneratedText(patientInfo?.phone, context.phone),
      registrationStatus: useGeneratedText(
        patientInfo?.registrationStatus,
        'SUBMITTED',
      ),
      remark: useGeneratedText(
        patientInfo?.remark,
        `${context.remark} 记录ID：${created.id}`,
      ),
      specimenType: useGeneratedText(
        patientInfo?.specimenType,
        context.specimenType,
      ),
      wardName: useGeneratedText(patientInfo?.wardName, context.wardName),
    },
    surgeryInfo: {
      buildingId: useGeneratedText(
        surgeryInfo?.buildingId,
        context.surgeryBuildingId,
      ),
      clinicalFindings: useGeneratedText(
        surgeryInfo?.clinicalFindings,
        context.clinicalFindings,
      ),
      fixativeType: useGeneratedText(
        surgeryInfo?.fixativeType,
        context.fixativeType,
      ),
      fixationPerson: useGeneratedText(
        surgeryInfo?.fixationPerson,
        context.fixationPerson,
      ),
      fixationTime: useGeneratedText(
        surgeryInfo?.fixationTime,
        context.fixationTime,
      ),
      roomId: useGeneratedText(surgeryInfo?.roomId, context.roomId),
      specimenRemovalTime: useGeneratedText(
        surgeryInfo?.specimenRemovalTime,
        context.specimenRemovalTime,
      ),
      surgeryName: useGeneratedText(
        surgeryInfo?.surgeryName,
        context.surgeryName,
      ),
    },
  };
}

export function isApplicationNoTooLong(applicationNo: string) {
  return normalizeApplicationNo(applicationNo).length > 64;
}
