import type { PathologyScreenSummary } from '../types/pathology-screen';

export const pathologyScreenStaticSummary: PathologyScreenSummary = {
  title: '智慧病理数据驾驶舱',
  centerMetrics: [
    { label: '全年病例总数(例)', value: '158463' },
    { label: '上月病例总数(例)', value: '13226' },
    { label: '上月报告及时率', value: '100%' },
  ],
  centerStageNodes: [
    { label: '切片', value: '2323', x: 212, y: 212 },
    { label: '特检', value: '2002', x: 430, y: 142 },
    { label: '归档', value: '2001', x: 620, y: 142 },
    { label: '报告', value: '2123', x: 798, y: 212 },
  ],
  topLeftLegend: ['24小时内修改率', '24小时后修改率', '全部修改率'],
  topLeftBars: [
    {
      label: '12月',
      darkValue: '0.82%',
      lightValue: '0.10%',
      tealValue: '1.20%',
    },
    {
      label: '01月',
      darkValue: '0.92%',
      lightValue: '0.20%',
      tealValue: '0.83%',
    },
    {
      label: '02月',
      darkValue: '1.03%',
      lightValue: '0.20%',
      tealValue: '0.80%',
    },
    {
      label: '03月',
      darkValue: '1.00%',
      lightValue: '0.10%',
      tealValue: '0.94%',
    },
  ],
  topLeftRateItems: [
    { label: '规范化固定率', value: '98.00%' },
    { label: 'HE染色切片优良率', value: '100.00%' },
    { label: '免疫组化染色切片优良率', value: '100.00%' },
    { label: '冰冻切片染色优良率', value: '100.00%' },
    { label: '细胞学制片染色优良率', value: '99.00%' },
    { label: '特殊染色制片优良率', value: '100.00%' },
  ],
  reportTypesSummary: {
    totalKinds: '27',
    totalWorkload: '59744例',
  },
  reportTypes: [
    { label: 'NGS基因检测(简版6无TMB无MSI)', value: '17' },
    { label: '结直肠癌V2', value: '562' },
    { label: 'NGS基因检测(简版3无胚系)', value: '8' },
    { label: 'Fish报告', value: '1256' },
    { label: '肺癌病理结构化V1', value: '147' },
    { label: 'NGS基因检测(简版4无TMB无胚系)', value: '57' },
    { label: '非妇科细胞学', value: '5213' },
    { label: '肺癌病理结构化V2', value: '783' },
    { label: '细胞学刮片', value: '12806' },
    { label: '妇科液基细胞学DNA', value: '12629' },
    { label: '食管癌结构化V1', value: '193' },
    { label: '肺癌+基因', value: '291' },
  ],
  rightTableRows: [
    {
      label: 'PC',
      january: '509',
      february: '561',
      ratio: '↑10.22%',
      ratioTone: 'up',
    },
    {
      label: 'V',
      january: '122',
      february: '123',
      ratio: '↑0.82%',
      ratioTone: 'up',
    },
    {
      label: '免疫组化(项)',
      january: '12105',
      february: '11006',
      ratio: '↓9.08%',
      ratioTone: 'down',
    },
    {
      label: 'FISH(例)',
      january: '78',
      february: '92',
      ratio: '↑17.95%',
      ratioTone: 'up',
    },
    {
      label: 'EBER(例)',
      january: '145',
      february: '141',
      ratio: '↓2.76%',
      ratioTone: 'down',
    },
    {
      label: '免疫荧光(例)',
      january: '0',
      february: '0',
      ratio: '-',
      ratioTone: 'neutral',
    },
    {
      label: '特殊染色(项)',
      january: '772',
      february: '745',
      ratio: '↓3.52%',
      ratioTone: 'down',
    },
  ],
  topRightRateItems: [
    { label: '总报告及时率', value: '100.00%' },
    { label: '细胞学病理诊断及时率', value: '100.00%' },
    { label: '组织病理诊断及时率', value: '95.00%' },
    { label: '术中快速病理诊断及时率', value: '100.00%' },
    { label: '术中快速诊断与石蜡诊断符合率', value: '100.00%' },
    { label: 'HE细胞学阳性结果与活检病理诊断符合率', value: '100.00%' },
  ],
  bottomLeftBars: [
    { label: '2021年', darkValue: '97%', lightValue: '93%', tealValue: '90%' },
    { label: '2022年', darkValue: '99%', lightValue: '97%', tealValue: '95%' },
    { label: '2023年', darkValue: '99%', lightValue: '98%', tealValue: '97%' },
  ],
  staffMetrics: [
    { label: '每百张病床病理技术员数', value: '0.77', accentValue: '人' },
    { label: '每百张病床病理医师人数', value: '1.19', accentValue: '人' },
  ],
  staffGauges: [
    { label: '近三年临床医师满意度', value: 97.6, year: '2021' },
    { label: '近三年临床医师满意度', value: 99.2, year: '2022' },
    { label: '近三年临床医师满意度', value: 100, year: '2023' },
  ],
  bottomRightLegend: [
    '病理诊断及时率',
    '组织病理诊断及时率',
    '冰冻快速病理诊断及时率',
  ],
  bottomRightBars: [
    { label: '2021年', darkValue: '96%', lightValue: '95%', tealValue: '96%' },
    { label: '2022年', darkValue: '98%', lightValue: '97%', tealValue: '98%' },
    { label: '2023年', darkValue: '99%', lightValue: '98%', tealValue: '100%' },
  ],
};
